name: Build and run Docker container

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image with branch and SHA tags
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
          docker build \
            -t ghcr.io/Kenneth-Pierloz/hello-world-nginx:${BRANCH_NAME} \
            -t ghcr.io/Kenneth-Pierloz/hello-world-nginx:${GITHUB_SHA} .
            .

      - name: Start Docker container
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
          docker run -d --name hello-world-nginx -p 8080:80 ghcr.io/Kenneth-Pierloz/hello-world-nginx:${BRANCH_NAME}

      - name: Verify container is running
        run: |
          sleep 5
          curl -f http://localhost:8080

      - name: Stop container
        if: always()
        run: docker stop hello-world-nginx || true